version: 2.1

executors:
  node:
    docker:
      - image: cimg/node:21.7.3-browsers
    working_directory: ~/repo
    environment:
      GIT_AUTHOR_EMAIL: serhii.ponomarenko.jobs@gmail.com
      GIT_AUTHOR_NAME: tiptophelmet
      GIT_COMMITTER_EMAIL: serhii.ponomarenko.jobs@gmail.com
      GIT_COMMITTER_NAME: tiptophelmet

jobs:
  prepare:
    executor: node

    steps:
      - checkout

      - run: npm ci

      - persist_to_workspace:
          root: .
          paths:
            - "*"

  build:
    executor: node

    steps:
      - attach_workspace:
          at: .

      - run: npm run build

      - persist_to_workspace:
          root: .
          paths:
            - "declarations"
            - "dist"
            - "esnext"
            - "peer"
            - "standalone"
            - "styles"
            - "types"

  lint:
    executor: node

    steps:
      - attach_workspace:
          at: .

      - run: npm run lint

  release:
    executor: node

    steps:
      - attach_workspace:
          at: .

      - run:
          name: Prepare NPM
          command: |
            npm set //registry.npmjs.org/:_authToken=$NPM_TOKEN

      - run:
          name: Release
          command: |
            npx semantic-release

workflows:
  version: 2

  build:
    jobs:
      - prepare

      - build:
          requires:
            - prepare

      - release:
          requires:
            - prepare
            - build
            # - lint
          filters:
            branches:
              only:
                - master
